version: 2

models:
  - name: data_test_numeric_constraints
    columns:
    - name: vat_pct
      tests:
        - dbt_utils.numeric_constraints:
            gte: 0
            ne: 0.5
            lt: 1
        - dbt_utils.numeric_constraints:
            eq: 0
            condition: "(status = 'done') and (type = 'international')"

  - name: data_test_unique_where
    columns:
    - name: part
      tests:
        - unique_where:
            where: "car = 'panamera'"
        - unique_where:
            where: "car = 'golf'"
